#Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)

In [2]:
import numpy as np

#THE BASICS :

#initialize array
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)

one dimensional array : [1 2 3]
two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [4]:
#Get Dimension
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)

dimension of a : 1
dimension of b : 2


In [5]:
#Get Shape
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)

shape of a : (3,)
shape of b : (2, 4)


In [6]:
#Get  Type
print("a type is :",a.dtype)

a type is : int16


In [8]:
#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;

size of a : 3


In [9]:
#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)

a item size : 2
total size is a: 6


In [10]:
#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC
#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]

np.float64(4.2)

In [11]:
#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:1]);

row : [2.1]


In [12]:
#Get specific column[:,column]
print("column :",b[:,1])

column : [2. 3.]


In [13]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])

subset of specific row [3.  4.5]


In [14]:
#change element
b[1,2]=8
print(b)

b[:,2]=[9,4]
b

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

In [2]:
 int(1.2)

1

# 3-D Example


In [9]:
c=np.array([[
    [1,2],[2,3]
    ],
    [
        [3,4],[4,5]
    ]
        ])

In [10]:
c

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]]])

In [11]:
type(c)

numpy.ndarray

In [12]:
c.ndim

3

In [13]:
c.shape

(2, 2, 2)

In [14]:
c.size

8

## Calculate the memory space took c numpy array

In [15]:
c.dtype

dtype('int64')

In [17]:
c.itemsize*c.size

64

In [18]:
c

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]]])

In [22]:
#Get specific element(work outside in)
print("specified element is:",c[1,0])

specified element is: [3 4]


### Initilizing different type of array

In [5]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
zm=np.zeros((3,4))

In [8]:
zm.ndim

2

In [9]:
zm.shape

(3, 4)

# ALL 1's Matrix

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
ones=np.ones((3,3),dtype="int16")

In [14]:
ones[1,1]=100
ones

array([[  1,   1,   1],
       [  1, 100,   1],
       [  1,   1,   1]], dtype=int16)

In [21]:
#Any other number
n100=np.full((4,5),100,dtype="float")
n100


array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

reuse the already existing array and assign one value to 

In [23]:
np.full_like(n100,200,dtype="float")

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

random matrix

In [24]:
np.random.random_sample((2,3))

array([[0.13266405, 0.6341536 , 0.94665779],
       [0.62226157, 0.20686244, 0.80787244]])

In [26]:
np.random.rand(2,3)

array([[0.11649391, 0.90406687, 0.84598536],
       [0.87635937, 0.77317654, 0.1547187 ]])

In [27]:
np.random.randint(6,9,size=(3,3))

array([[8, 6, 6],
       [7, 8, 6],
       [7, 8, 6]], dtype=int32)

In [31]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])